/** Yandex Delivery buyurtma holatlari (o'zbekcha) — brauzerda ham ishlatiladi */
export const YANDEX_STATUS_UZ: Record<string, string> = {
  new: "Yaratildi",
  estimating: "Narx hisoblanmoqda",
  estimating_failed: "Narxni hisoblab bo'lmadi",
  ready_for_approval: "Tasdiq kutilmoqda",
  accepted: "Qabul qilindi",
  performer_lookup: "Kuryer qidirilmoqda",
  performer_draft: "Kuryer qidirilmoqda",
  performer_found: "Kuryer topildi",
  performer_not_found: "Kuryer topilmadi",
  pickup_arrived: "Kuryer do'konga keldi",
  ready_for_pickup_confirmation: "Kuryer olib ketmoqda",
  pickuped: "Kuryer yo'lda",
  delivery_arrived: "Kuryer mijozga yetib keldi",
  ready_for_delivery_confirmation: "Topshirilmoqda",
  pay_waiting: "To'lov kutilmoqda",
  delivered: "Yetkazildi",
  delivered_finish: "Yetkazildi",
  returning: "Qaytarilmoqda",
  return_arrived: "Qaytarib keltirildi",
  returned: "Qaytarildi",
  returned_finish: "Qaytarildi",
  cancelled: "Bekor qilindi",
  cancelled_with_payment: "Bekor qilindi (pullik)",
  cancelled_by_taxi: "Yandex bekor qildi",
  cancelled_with_items_on_hands: "Bekor qilindi",
  failed: "Xatolik",
};

